title: My Existing Site
description: Your site description here.
baseurl: ""  # Leave blank for user or organization sites
url: "https://lantzounato.github.io"  # Replace with your GitHub username
theme: minima  # You can choose any Jekyll-supported theme
feed:
  path: /feed.xml
plugins:
  - jekyll-feed
